[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "runboat"
authors = [{name = "St\u00e9phane Bidoul", email = "stephane.bidoul@gmail.com"}]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "fastapi",
    "gunicorn",
    "httpx",
    "jinja2",
    "kubernetes",
    "rich",
    "uvicorn",
]
dynamic = ["version", "description"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-dotenv",
]

[project.urls]
Home = "https://github.com/sbidoul/runboat"

[tool.isort]
profile = 'black'

[tool.pytest.ini_options]
env_override_existing_values = 1
env_files = [".env.test"]

# flake8 config is in .flake8
